### ISSUE TITLE
the meaning of each variable in the analysis

### ISSUE THREAD

**Issue by Eugene-xyHe** [jrs95/nlmr#5]
Thank you very much for providing this useful R package.

Sorry to be a bother. I’m a clinical medical student and i'm doing a research on nonlinear association of BMI and other phenotypes. But I still have some quenstion about it.

First, I noticed that in this analysis, we need "x" for exposure, i'm not sure if that was the original phenotype data or the GRS we calculated. Second, I wonder if "g" represents the genotype of one variant, which one would it be? i don't know how to choose it since we usually use the whole significant variants to calculate the GRS of a phenotype.

I will be appreciated for your reply, thank you very much again!

**Comment by ghost** [comment]
Thank you very much for providing this useful R package.

Sorry to be a bother. I’m a clinical medical student and I'm doing a nlmr analysis with this package, when I input my file correctly I got a error message of " fractional polynomial models require the exposure to be >>1 ". I am not sure why the exposure have to ">>0"， the condition to pass this check is "X >= 1", but my data of exposure had been log(base = exp(1)) transformed and scaled, and even in the original data the exposure is not all >= 1. Can you give some advices for deal this situation?

Thank you very much!

**Comment by jrs95** [comment]
Hi,

x = original exposure
g = genetic instrument, this can be a genetic variant or a genetic risk score

Fractional polynomial modelling in general requires the independent variable (in this case x) to be positive. This is because some of the polynomials are not defined on the natural number line for negative values of x. There is also an issue with log(x) when x is close to 0 as log(0)=-∞.

Hope this helps,

James
